# Database Configuration
spring.datasource.url=jdbc:h2:mem:jobdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (so you can see the DB in browser at /h2-console)
spring.h2.console.enabled=true

# Prevent the app from stopping if a runner fails
spring.main.terminate-on-registration-errors=false
